### ISSUE TITLE
CIを用意したい

### ISSUE THREAD

**Issue by Kevinrobot34** [Kevinrobot34/dotfiles#6]
github actions で
```yaml
...
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
...
```

* https://dev.classmethod.jp/articles/joined-mac-dotfiles-customize/ より

とすれば MacOS を使って動かせるので、テストになって嬉しい
